# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Tests
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci

      # actual work
      - name: Run type checking
        run: npm run check
      - name: Run linting
        run: npm run lint
